tap "mongodb/brew"

brew "curl"
brew "fastfetch"
brew "findutils"
brew "gcc"
brew "git"
brew "htop"
brew "lua"
brew "maven"
brew "mongodb/brew/mongodb-community@8.0"
brew "neovim"
brew "nginx", restart_service: :changed
brew "node"
brew "ripgrep"
brew "stow"
brew "tmux"
brew "tree"
brew "vitetris"
brew "youtube-dl"

cask "appcleaner"
cask "coconutbattery"
cask "codex"
cask "discord"
cask "gifcapture"
cask "gimp"
cask "handbrake-app"
cask "insomnia"
cask "mongodb-compass"
cask "mountain-duck"
cask "omnidisksweeper"
cask "stats"
cask "transmission"
cask "vlc"
cask "zed"
